language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  
cache: pip
install:
  - pip install -r requirements.txt
  - sudo apt-get update \
  - && sudo apt-get install -y build-essential git libexpat1-dev libssl-dev zlib1g-dev \
  - libncurses5-dev libbz2-dev liblzma-dev \
  - libsqlite3-dev libffi-dev tcl-dev linux-headers-generic libgdbm-dev \
  - libreadline-dev tk tk-dev

  - git clone https://github.com/python/cpython.git
  - cd cpython && ./configure --prefix=/usr \
  --enable-loadable-sqlite-extensions \
  --enable-shared \
  --with-lto \
  --enable-optimizations \
  --with-system-expat \
  --with-system-ffi \
  --enable-ipv6 --with-threads --with-pydebug --disable-rpath \&& make \
  && sudo make install
  
script:
  - python ex11..py
  - sleep 3
  - python ex12..py  
  - sleep 3
  - python ex13..py  
  - sleep 3
  - python ex14..py  
  - sleep 3
  - python ex15..py  
  - sleep 3
  - python ex16..py  
  - sleep 3
  - python ex17..py  
  - sleep 3
  - python ex18..py  
  
