language: python
sudo: false

python:
  - "2.7"
  
cache: pip

install:
    - pip install -r requirements.txt
    - sudo apt-get install python-pip
    - sudo apt-get install build-essential libssl-dev libffi-dev python-dev
    - pip install pytest
    
script:
  - python ex11.py  < answers.txt
  - python ex12.py  < answers.txt
  - python ex13.py stuff things that < answers.txt
  - python ex14.py  test < answes2.txt
  - python ex15.py ex15_sample.txt < anwer.txt  
#   - sleep 3
#   - python ex16.py  
#   - sleep 3
#   - python ex17.py  
#   - sleep 3
#   - python ex18.py  
#   - python escapeCharector.py

