language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  
cache: pip

install:
    - pip install -r requirements.txt
    - sudo apt install python-pip
    - sudo apt install build-essential libssl-dev libffi-dev python-dev
    - pip install pytest
    
script:
  - python ex11.py  < answers.txt
  - sleep 3
  - python ex12.py  < answers.txt
  - sleep 3
  - python ex13.py  < answers.txt
#   - sleep 3
#   - python ex14.py  
#   - sleep 3
#   - python ex15.py  
#   - sleep 3
#   - python ex16.py  
#   - sleep 3
#   - python ex17.py  
#   - sleep 3
#   - python ex18.py  
#   - python escapeCharector.py

