language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  
cache: pip
install:
  - pip install -r requirements.txt
  
script:
  - python ex11..py
  - sleep 3
  - python ex12..py  
  - sleep 3
  - python ex13..py  
  - sleep 3
  - python ex14..py  
  - sleep 3
  - python ex15..py  
  - sleep 3
  - python ex16..py  
  - sleep 3
  - python ex17..py  
  - sleep 3
  - python ex18..py  
  
